export type WordClass = 'noun' | 'verb' | 'adjective' | 'function'

const groups: Record<WordClass, string> = {
  function: `I you he she it we they me him her us them my your his our their this that these those who what where when why how and but or because if although while so than as not yes no very too also only even again already still never always often sometimes usually perhaps here there now then in on at by for from to with without about between through during before after above below near of a an the some any many much few all each every both another`,
  noun: `person people man woman child boy girl baby friend family mother father parent sister brother husband wife name age life death world country city town village street home house room door window floor wall roof garden school class lesson teacher student book page word question answer idea story language letter number job work office company business shop market money price food water bread rice meat fish egg milk cheese fruit apple banana orange vegetable potato tomato meal breakfast lunch dinner coffee tea sugar salt table chair bed clothes shirt coat dress shoe bag phone computer internet picture music song film game sport ball team player car bus train plane airport station road bicycle boat journey trip holiday hotel beach mountain river sea lake forest tree flower animal dog cat bird horse weather rain snow wind sun sky day week month year morning afternoon evening night today tomorrow yesterday time hour minute second birthday party gift color red blue green black white body head face eye ear nose mouth tooth hair hand arm leg foot heart health doctor hospital medicine problem accident fire police place thing way part side end beginning reason result example fact change difference kind type group point government law war peace history future past earth field nation liberty freedom art science nature energy air ground building church restaurant bank library park farm factory bridge map north south east west`,
  verb: `be have do say tell speak talk ask answer know think understand remember forget learn teach read write spell mean use make create build draw show see look watch hear listen feel touch smell taste want need like love hate prefer enjoy hope wish try help work play move run walk sit stand lie live die give take bring carry put keep hold find lose buy sell pay cost send receive meet visit stay leave come go travel arrive return start begin finish stop continue wait happen become grow turn change open close break cut wash clean cook eat drink sleep wake wear drive ride fly swim dance sing smile laugh cry win lose pass fail choose decide plan agree disagree believe seem appear follow lead call explain describe compare share spend save kill fight protect remember forget translate dedicate perish resolve bless advance`,
  adjective: `good bad big small long short high low old young new early late fast slow hot cold warm cool easy difficult hard important possible impossible right wrong true false same different full empty open closed happy sad angry afraid tired busy free ready careful dangerous safe healthy sick strong weak rich poor beautiful ugly clean dirty quiet loud bright dark kind nice friendly polite brave clever stupid interesting boring funny serious special normal famous popular sure clear simple common great final unfinished equal dead living national international local public private personal available expensive cheap modern traditional useful necessary real whole enough several own other next last first second best better worse near far left correct favorite`,
}

const irregularPast: Record<string, string> = { be:'was', have:'had', do:'did', say:'said', tell:'told', know:'knew', think:'thought', see:'saw', hear:'heard', feel:'felt', make:'made', take:'took', bring:'brought', find:'found', lose:'lost', buy:'bought', sell:'sold', send:'sent', meet:'met', leave:'left', come:'came', go:'went', become:'became', give:'gave', eat:'ate', drink:'drank', sleep:'slept', wake:'woke', wear:'wore', drive:'drove', ride:'rode', fly:'flew', swim:'swam', sing:'sang', win:'won', pay:'paid', cost:'cost', read:'read', write:'wrote', speak:'spoke', build:'built' }
const plural = (word: string) => word.endsWith('y') ? `${word.slice(0,-1)}ies` : /(?:s|x|ch|sh)$/.test(word) ? `${word}es` : `${word}s`
const past = (word: string) => irregularPast[word] ?? (word.endsWith('e') ? `${word}d` : word.endsWith('y') ? `${word.slice(0,-1)}ied` : `${word}ed`)
const ing = (word: string) => `${word.endsWith('e') && word !== 'be' ? word.slice(0,-1) : word}ing`

export interface VocabularyItem { english: string; category: WordClass; form: 'root' | 'plural' | 'past' | 'continuous' }

export const b1Vocabulary: VocabularyItem[] = Object.entries(groups).flatMap(([category, words]) => {
  const wordClass = category as WordClass
  return words.split(/\s+/).flatMap((english): VocabularyItem[] => {
    const root: VocabularyItem = { english, category: wordClass, form: 'root' }
    if (wordClass === 'noun') return [root, { english: plural(english), category: wordClass, form: 'plural' }]
    if (wordClass === 'verb') return [root, { english: past(english), category: wordClass, form: 'past' }, { english: ing(english), category: wordClass, form: 'continuous' }]
    return [root]
  })
})
