export type UiLanguage = 'en' | 'ru'

const russian: Record<string, string> = {
  'Ask a linguist': 'Спросить лингвиста',
  'A small language laboratory': 'Маленькая языковая лаборатория',
  'Constructed language generator': 'Генератор искусственных языков',
  'Give a new language': 'Подарите новому языку',
  'its first words.': 'его первые слова.',
  'Choose its sounds and grammar. We’ll build a vocabulary and let it speak Article 1 of the Universal Declaration of Human Rights for the first time.': 'Выберите звуки и грамматику. Мы создадим словарь и впервые позволим языку заговорить словами статьи 1 Всеобщей декларации прав человека.',
  'Made for curious linguists · Every generation is unique': 'Создано для любознательных лингвистов · Каждый язык уникален',
  'Log in or sign up': 'Войти или зарегистрироваться', 'Log in': 'Войти', 'Sign up': 'Регистрация',
  'Continue with Google': 'Продолжить с Google', 'or use email': 'или войдите по почте', Email: 'Электронная почта',
  'Password (6+ characters)': 'Пароль (не менее 6 символов)', 'Please wait…': 'Подождите…', 'Create account': 'Создать аккаунт',
  'Check your email to confirm your account, then log in.': 'Подтвердите аккаунт по ссылке в письме, затем войдите.',
  'Could not load saved languages.': 'Не удалось загрузить сохранённые языки.', 'No saved languages yet.': 'Сохранённых языков пока нет.',
  'Sign out': 'Выйти', 'Save and load': 'Сохранение и загрузка', 'Save current': 'Сохранить текущий',
  'Language saved.': 'Язык сохранён.', 'Could not save this language.': 'Не удалось сохранить язык.', 'Could not delete that save.': 'Не удалось удалить сохранение.',
  'Log in from the menu under the Glossopoem logo to save this language.': 'Войдите через меню под логотипом Glossopoem, чтобы сохранить язык.',
  Inspiration: 'Вдохновение', Sounds: 'Звуки', 'Sound rules': 'Правила звучания', Grammar: 'Грамматика', Review: 'Проверка',
  'Builder steps': 'Шаги создания', Step: 'Шаг', of: 'из', Back: 'Назад', Continue: 'Продолжить',
  'Ready to meet your language?': 'Готовы познакомиться со своим языком?', 'All choices remain editable from the overview page.': 'Все настройки можно изменить на странице обзора.',
  'Complete the missing sound and grammar choices before generating.': 'Заполните недостающие настройки звуков и грамматики.', 'Generate my language': 'Создать мой язык',
  'Language family inspiration': 'Вдохновение языковой семьёй', 'Choose a family as a starting point, or build freely from scratch.': 'Выберите языковую семью как основу или создайте всё с нуля.',
  None: 'Нет', 'Vocabulary inspiration': 'Вдохновение для словаря', selected: 'выбрано', none: 'нет',
  'Choose any number of families. This only inspires a few core roots; sounds and grammar stay independent.': 'Выберите любое число семей. Они повлияют лишь на несколько основных корней; звуки и грамматика останутся независимыми.',
  'Clear vocabulary inspiration': 'Очистить вдохновение для словаря', Vowels: 'Гласные', Consonants: 'Согласные',
  'The chart moves from sounds made at the front of your mouth to the back.': 'Таблица идёт от звуков, произносимых в передней части рта, к задней.',
  'Voiced means your throat vibrates. A plosive briefly blocks the air; a fricative squeezes it.': 'При звонких звуках вибрирует горло. Взрывные ненадолго перекрывают воздух, а щелевые сужают его поток.',
  Phonotactics: 'Фонотактика', 'Phonotactics are rules about where sounds may appear. Select which consonants can begin or end a syllable.': 'Фонотактика определяет, где могут встречаться звуки. Выберите согласные, которыми может начинаться или заканчиваться слог.',
  'Allowed at the beginning': 'Разрешены в начале', 'Allowed at the end': 'Разрешены в конце',
  'Morphological regularity': 'Морфологическая регулярность', 'Controls how consistently nouns and verbs follow their usual patterns.': 'Определяет, насколько последовательно существительные и глаголы подчиняются правилам.',
  'Highly irregular': 'Очень нерегулярный', 'Mostly irregular': 'Скорее нерегулярный', Mixed: 'Смешанный', 'Mostly regular': 'Скорее регулярный', 'Highly regular': 'Очень регулярный',
  'Language type': 'Тип языка', 'Syllable structure': 'Структура слога', 'Word order': 'Порядок слов', 'Grammatical gender / noun classes': 'Грамматический род / классы существительных',
  Articles: 'Артикли', 'Verb conjugation': 'Спряжение глаголов', 'Consonant clusters': 'Сочетания согласных', 'Vowel sequences': 'Сочетания гласных', 'Vowel harmony': 'Гармония гласных',
  Analytic: 'Аналитический', Agglutinative: 'Агглютинативный', Fusional: 'Флективный', Polysynthetic: 'Полисинтетический', Isolating: 'Изолирующий', Introflexive: 'Интрофлективный', Oligosynthetic: 'Олигосинтетический',
  'No clusters': 'Без сочетаний', 'Rising sonority': 'Восходящая звучность', 'Falling sonority': 'Нисходящая звучность', Unrestricted: 'Без ограничений',
  'No sequences': 'Без сочетаний', 'Long vowels': 'Долгие гласные', Diphthongs: 'Дифтонги', Hiatus: 'Хиатус', 'Harmony-bound': 'По гармонии',
  One: 'Один', Gendered: 'По роду', 'One + plural': 'Один + множественный', 'Gendered + plural': 'По роду + множественный', 'Tense + person': 'Время + лицо',
  'Grammatical cases': 'Грамматические падежи', 'Cases show a noun\'s role in a sentence. Select none for a language without noun cases.': 'Падежи показывают роль существительного в предложении. Не выбирайте ничего для языка без падежей.',
  'No case marking.': 'Падежных показателей нет.', Nominative: 'Именительный', Accusative: 'Винительный', Genitive: 'Родительный', Dative: 'Дательный', Instrumental: 'Творительный', Locative: 'Местный', Ablative: 'Исходный', Allative: 'Направительный', Elative: 'Изнутри', Illative: 'Внутрь', Adessive: 'Внешнеместный', Inessive: 'Внутриместный', Essive: 'Эссив', Translative: 'Транслатив', Vocative: 'Звательный', Comitative: 'Совместный',
  'Your language will appear here': 'Здесь появится ваш язык', 'Choose an inspiration, build its sound inventory, and set its grammar to begin.': 'Выберите источник вдохновения, звуки и грамматику, чтобы начать.',
  'Your language is called': 'Ваш язык называется', 'Modify…': 'Изменить…', 'Modify language settings': 'Изменить настройки языка', 'Generate again': 'Создать заново', 'Review all': 'Проверить всё',
  'Latin · diacritics': 'Латиница · диакритика', 'No gender': 'Без рода', 'No articles': 'Без артиклей', 'No conjugation': 'Без спряжения', 'Tense + person conjugation': 'Спряжение по времени и лицу', 'Original vocabulary': 'Оригинальный словарь', 'No vowel harmony': 'Без гармонии гласных',
  'Word edges:': 'Границы слова:', 'starts with': 'начало:', 'ends with': 'конец:', 'vowels only': 'только гласные',
  'A working vocabulary': 'Рабочий словарь', 'Universal Declaration of Human Rights': 'Всеобщая декларация прав человека', 'Article 1 · All human beings are born free and equal in dignity and rights': 'Статья 1 · Все люди рождаются свободными и равными в своём достоинстве и правах',
  'Basic translator': 'Простой переводчик', English: 'Английский', 'Reverse translation': 'Сменить направление перевода', 'Type a sentence…': 'Введите предложение…', 'Translation appears here.': 'Здесь появится перевод.',
  'This word-for-word translator preserves punctuation. Unknown words stay unchanged.': 'Этот пословный переводчик сохраняет пунктуацию. Неизвестные слова не изменяются.',
  Dictionary: 'Словарь', 'Search English or generated words…': 'Искать английские или созданные слова…', 'No matching word yet.': 'Подходящих слов пока нет.', Person: 'Лицо', Present: 'Настоящее', Past: 'Прошедшее', Future: 'Будущее',
  'Language-family inspiration': 'Вдохновение языковой семьёй', 'Sets a coordinated starting point for sounds and grammar.': 'Задаёт согласованную основу для звуков и грамматики.',
  'Grammar mostly uses separate helper words.': 'Грамматика в основном использует отдельные служебные слова.', 'Words rarely change their form.': 'Слова почти не меняют форму.',
  'Clear pieces stack onto a word, one meaning each.': 'К слову последовательно присоединяются части, каждая со своим значением.', 'One ending can carry several meanings.': 'Одно окончание может передавать несколько значений.',
  'A whole sentence can fit inside one long word.': 'Целое предложение может помещаться в одном длинном слове.', 'Grammar changes vowels inside a word.': 'Грамматика меняет гласные внутри слова.', 'A tiny stock of roots combines into many ideas.': 'Небольшой набор корней сочетаниями выражает множество понятий.',
  'Consonant + vowel. Simple and open.': 'Согласный + гласный. Простая открытая структура.', 'Consonant + vowel + consonant, as in cat.': 'Согласный + гласный + согласный, как в слове cat.', 'One opening consonant and two at the end.': 'Один согласный в начале и два в конце.', 'Two opening consonants + vowel.': 'Два начальных согласных + гласный.', 'A long vowel or diphthong.': 'Долгий гласный или дифтонг.', 'Two opening consonants and one final consonant.': 'Два согласных в начале и один в конце.',
  'Nouns have no grammatical gender.': 'У существительных нет грамматического рода.', 'Two agreement groups.': 'Две группы согласования.', 'Often masculine, feminine, and neuter.': 'Обычно мужской, женский и средний род.', 'Four noun agreement groups.': 'Четыре группы согласования существительных.', 'A larger noun-class system.': 'Расширенная система классов существительных.',
  'The language does not use articles.': 'Язык не использует артикли.', 'One article is used for every noun.': 'Один артикль используется со всеми существительными.', 'Articles agree with noun gender.': 'Артикли согласуются с родом существительного.', 'Separate singular and plural articles.': 'Отдельные артикли для единственного и множественного числа.', 'Articles agree with gender and number.': 'Артикли согласуются по роду и числу.',
  'The verb changes for who acts and when.': 'Глагол меняется в зависимости от действующего лица и времени.', 'The verb never changes; separate words show person and time, like Indonesian.': 'Глагол не меняется; лицо и время выражаются отдельными словами, как в индонезийском.',
  'Only one consonant at a syllable edge.': 'На границе слога допускается только один согласный.', 'Clusters open toward the vowel, as in play.': 'Сочетания раскрываются к гласному, как в слове play.', 'Clusters create sharper syllable edges.': 'Сочетания создают более резкие границы слога.', 'Consonants may combine freely.': 'Согласные могут сочетаться свободно.',
  'Vowels do not occur side by side.': 'Гласные не встречаются рядом.', 'Doubled vowels create longer sounds.': 'Удвоенные гласные образуют долгие звуки.', 'Two vowels glide together.': 'Два гласных плавно сливаются.', 'Adjacent vowels form separate syllables.': 'Соседние гласные образуют разные слоги.', 'Sequences stay inside one harmony group.': 'Сочетания остаются внутри одной группы гармонии.',
  'Any selected vowels may appear together.': 'Любые выбранные гласные могут встречаться вместе.', 'Words keep front or back vowels together.': 'В слове сочетаются гласные только переднего или только заднего ряда.', 'Central vowels may join either group.': 'Центральные гласные могут присоединяться к любой группе.', 'Vowels agree in lip rounding.': 'Гласные согласуются по огублённости.', 'Vowels match position and rounding.': 'Гласные согласуются по ряду и огублённости.', 'Vowels keep a similar tongue height.': 'Гласные сохраняют близкий подъём языка.', 'Vowels agree in tongue-root position.': 'Гласные согласуются по положению корня языка.',
  'Front / back': 'Передние / задние', 'Front / back + neutral': 'Передние / задние + нейтральные', Rounding: 'Огублённость', 'Front / back + rounding': 'Ряд + огублённость', Height: 'Подъём', 'Advanced tongue root (ATR)': 'Выдвинутый корень языка (ATR)',
  'S = subject · V = verb · O = object': 'S = подлежащее · V = глагол · O = дополнение',
  'The subject doing the action: “the child runs.”': 'Субъект, совершающий действие: «ребёнок бежит».', 'The direct object receiving the action: “I see the child.”': 'Прямое дополнение, на которое направлено действие: «я вижу ребёнка».', 'Possession, belonging, or origin: “the child’s book.”': 'Владение, принадлежность или происхождение: «книга ребёнка».', 'The recipient or indirect object: “give it to the child.”': 'Получатель или косвенное дополнение: «дай это ребёнку».', 'The tool or means used: “write with a pen.”': 'Орудие или средство действия: «писать ручкой».', 'A general location or topic: “at home” or “about music.”': 'Место или тема: «дома» или «о музыке».', 'Movement away from a place: “from the house.”': 'Движение от места: «из дома».', 'Movement toward or onto a place: “to the house.”': 'Движение к месту или на него: «к дому».', 'Movement out from inside something: “out of the house.”': 'Движение изнутри наружу: «из дома».', 'Movement into something: “into the house.”': 'Движение внутрь: «в дом».', 'Being on, at, or near something: “on the table.”': 'Нахождение на чём-либо или рядом: «на столе».', 'Being inside something: “in the house.”': 'Нахождение внутри: «в доме».', 'A temporary state or role: “as a teacher.”': 'Временное состояние или роль: «в качестве учителя».', 'A change into a new state: “become a teacher.”': 'Переход в новое состояние: «стать учителем».', 'Directly addressing someone: “O friend!”': 'Прямое обращение: «О, друг!»', 'Accompaniment or togetherness: “with a friend.”': 'Совместность или сопровождение: «с другом».',
  'Made by bringing both lips together.': 'Произносится смыканием обеих губ.', 'Lower lip touches the upper teeth.': 'Нижняя губа касается верхних зубов.', 'Tongue meets the teeth or the ridge just behind them.': 'Язык касается зубов или бугорка сразу за ними.', 'Tongue rises toward the hard roof of the mouth.': 'Язык поднимается к твёрдому нёбу.', 'The tongue tip curls slightly backward toward the roof of the mouth.': 'Кончик языка слегка загибается назад к нёбу.', 'Back of the tongue approaches the soft palate or uvula.': 'Задняя часть языка приближается к мягкому нёбу или язычку.', 'Made down in the throat, at the vocal folds.': 'Произносится в гортани, у голосовых складок.', 'Air hisses around one or both sides of the tongue.': 'Воздух с шипением проходит вдоль одной или обеих сторон языка.', 'A sharp popping sound made by trapping and pushing air upward in the throat.': 'Резкий щелчок, создаваемый задержкой и выталкиванием воздуха вверх в горле.', 'The throat narrows deep behind the tongue. Common in Arabic and related languages.': 'Горло сужается глубоко за языком. Часто встречается в арабском и родственных языках.', 'The tongue traps and releases air with a pop, without breathing it out from the lungs.': 'Язык задерживает и высвобождает воздух со щелчком, без выдоха из лёгких.',
  Bilabial: 'Губно-губные', Labiodental: 'Губно-зубные', 'Dental & alveolar': 'Зубные и альвеолярные', 'Postalveolar & palatal': 'Постальвеолярные и палатальные', Retroflex: 'Ретрофлексные', 'Velar & uvular': 'Велярные и увулярные', Glottal: 'Гортанные', 'Lateral fricatives': 'Боковые фрикативные', Ejectives: 'Абруптивные', Pharyngeal: 'Фарингальные', Clicks: 'Щёлкающие',
  'Onsets · Germanic languages, for example, do not begin native words with /ŋ/.': 'Инициали · Например, в германских языках исконные слова не начинаются с /ŋ/.', 'Codas · Some languages permit many final sounds; others allow only a few.': 'Финали · Некоторые языки допускают много конечных звуков, другие — лишь несколько.',
  Germanic: 'Германская', Austronesian: 'Австронезийская', Semitic: 'Семитская', Turkic: 'Тюркская', Slavic: 'Славянская', Japonic: 'Японская', Romance: 'Романская', Indic: 'Индоарийская', Koreanic: 'Корейская', 'Niger-Congo': 'Нигер-конголезская', Uralic: 'Уральская', Athabaskan: 'Атабаскская',
  'Close front': 'Передний ряд, верхний подъём', 'Close front rounded': 'Передний ряд, верхний подъём, огублённый', 'Near-close front': 'Передний ряд, почти верхний подъём', 'Close-mid front': 'Передний ряд, средне-верхний подъём', 'Close-mid front rounded': 'Передний ряд, средне-верхний подъём, огублённый', 'Open-mid front': 'Передний ряд, средне-нижний подъём', 'Open-mid front rounded': 'Передний ряд, средне-нижний подъём, огублённый', 'Near-open front': 'Передний ряд, почти нижний подъём', 'Open front': 'Передний ряд, нижний подъём', Central: 'Средний ряд', 'Close central': 'Средний ряд, верхний подъём', 'Near-open central': 'Средний ряд, почти нижний подъём', 'Close back': 'Задний ряд, верхний подъём', 'Close back unrounded': 'Задний ряд, верхний подъём, неогублённый', 'Near-close back': 'Задний ряд, почти верхний подъём', 'Close-mid back': 'Задний ряд, средне-верхний подъём', 'Close-mid back unrounded': 'Задний ряд, средне-верхний подъём, неогублённый', 'Open-mid back': 'Задний ряд, средне-нижний подъём', 'Open back': 'Задний ряд, нижний подъём', 'Open back rounded': 'Задний ряд, нижний подъём, огублённый',
  'a curled-back t': 't с загнутым назад языком', 'a voiced curled-back d': 'звонкий d с загнутым назад языком', 'a curled-back n': 'n с загнутым назад языком', 'a curled-back l': 'l с загнутым назад языком', 'a curled-back sh': 'sh с загнутым назад языком', 'a deep k sound': 'глубокий звук k', 'the break in uh-oh': 'смычка в uh-oh', 'Welsh ll; voiceless': 'валлийский ll; глухой', 'a voiced, buzzing ll': 'звонкий жужжащий ll',
  'a popping p': 'щёлкающий p', 'a popping t': 'щёлкающий t', 'a popping k': 'щёлкающий k', 'a deep popping q': 'глубокий щёлкающий q', 'a strong, whispered h': 'сильный шёпотный h', 'a deep, voiced throat sound': 'глубокий звонкий горловой звук', 'a lip-smacking click': 'губной щелчок', 'a dental “tsk” click': 'зубной щелчок «ц-ц»', 'a sharp tongue-pop click': 'резкий щелчок языком', 'a click at the side of the tongue': 'боковой щелчок языком',
  'as in machine': 'как в русском «мир»', 'as in French tu': 'как во французском tu', 'as in bid': 'как в английском bid', 'as in café': 'как в испанском mesa', 'as in French deux': 'как во французском deux', 'as in bed': 'как в русском «это»', 'as in French sœur': 'как во французском sœur', 'as in cat': 'как в английском cat', 'as in father': 'как в русском «там»', 'as in about': 'как в безударном русском «молоко»', 'as in Polish ryba': 'как в русском «мы»', 'as in the end of comma': 'как в безударном русском «вода»', 'as in goose': 'как в русском «тут»', 'as in Turkish ılık': 'как в турецком ılık', 'as in book': 'как в английском book', 'as in go': 'как в русском «дом»', 'as in a back, unrounded o': 'как в болгарском път', 'as in thought': 'как в английском thought', 'as in palm': 'как в английском palm', 'as in British lot': 'как в британском английском lot',
  machine: 'русском «мир»', 'French tu': 'французском tu', bid: 'английском bid', 'café': 'испанском mesa', 'French deux': 'французском deux', bed: 'русском «это»', 'French sœur': 'французском sœur', cat: 'английском cat', father: 'русском «там»', about: 'безударном русском «молоко»', 'Polish ryba': 'русском «мы»', 'the end of comma': 'безударном русском «вода»', goose: 'русском «тут»', 'Turkish ılık': 'турецком ılık', book: 'английском book', go: 'русском «дом»', 'a back, unrounded o': 'болгарском път', thought: 'английском thought', palm: 'английском palm', 'British lot': 'британском английском lot',
  'spin; voiceless plosive': 'русское «спорт»; глухой взрывной', 'bin; voiced plosive': 'русское «банк»; звонкий взрывной', 'moon; nasal': 'русское «мама»; носовой', 'fine; voiceless fricative': 'русское «факт»; глухой щелевой', 'vine; voiced fricative': 'русское «вода»; звонкий щелевой', 'thin; voiceless': 'английское thin; глухой', 'this; voiced': 'английское this; звонкий', 'top; plosive': 'русское «там»; взрывной', 'dog; voiced plosive': 'русское «дом»; звонкий взрывной', 'sip; fricative': 'русское «сад»; щелевой', 'zip; voiced fricative': 'русское «зуб»; звонкий щелевой', 'no; nasal': 'русское «нос»; носовой', 'low; lateral': 'русское «лампа»; боковой', 'rolled r': 'русское «река»; раскатистый r', 'ship; voiceless': 'русское «шапка»; глухой', 'vision; voiced': 'русское «жук»; звонкий', 'chip; affricate': 'русское «чай»; аффриката', 'yes; glide': 'русское «яма»; аппроксимант',
  'cat; voiceless plosive': 'русское «кот»; глухой взрывной', 'go; voiced plosive': 'русское «год»; звонкий взрывной', 'sing; nasal': 'английское sing; носовой', 'Scottish loch': 'русское «хлеб»', 'hat; breathy fricative': 'английское hat; придыхательный щелевой',
}

export function translateUi(text: string, language: UiLanguage) {
  if (language === 'en') return text
  const trimmed = text.trim()
  if (russian[trimmed]) return text.replace(trimmed, russian[trimmed])
  const translatedFragments = Object.entries(russian)
    .filter(([english]) => english.length > 4 && text.includes(english))
    .sort(([first], [second]) => second.length - first.length)
    .reduce((result, [english, translation]) => result.split(english).join(translation), text)
  return translatedFragments
    .replace(/Saved languages \((\d+)\)/, 'Сохранённые языки ($1)')
    .replace(/Signed in as/, 'Вы вошли как')
    .replace(/(\d+) selected/, 'Выбрано: $1')
    .replace(/Step (\d+) of (\d+)/, 'Шаг $1 из $2')
    .replace(/(\d+) cases/, '$1 падежей').replace(/(\d+)% regular/, 'Регулярность: $1%')
    .replace(/(\d+) everyday words and forms/, '$1 повседневных слов и форм')
    .replace(/as in /g, 'как в ')
    .replace(/French /g, 'французском ')
    .replace(/Polish /g, 'польском ')
    .replace(/Turkish /g, 'турецком ')
    .replace(/British /g, 'британском ')
    .replace(/the end of comma/g, 'конце слова comma')
    .replace(/a back, unrounded o/g, 'задний неогублённый o')
}
